version: "3.8"

services:

  weather-app:
    build: .
    container_name: weather-app
    ports:
      - "8080:8080"
    environment:
      database.host: database
      DB_URL: jdbc:postgresql://database/weather_app_db
    depends_on:
      - database

  database:
    image: postgres
    container_name: weather-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_app_db
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: